#!/usr/bin/env bash
set -euo pipefail

# A/B Agent Test: Claude vs Codex
# Compares implementation plans generated by different AI agents for the same GitHub issue.
# Usage: ./scripts/ab-agent-test.sh https://github.com/owner/repo/issues/42

###############################################################################
# Configuration
###############################################################################
TIMEOUT_SECONDS="${TIMEOUT_SECONDS:-900}"
SCRIPT_DIR="$(cd "$(dirname "$(realpath "$0")")" && pwd)"
PROJECT_DIR="$(cd "$SCRIPT_DIR/.." && pwd)"
RESULTS_BASE="${RESULTS_BASE:-$PROJECT_DIR/results}"
REPO_BASE="$HOME/.yeti/ab-test/repos"
WT_BASE="$HOME/.yeti/ab-test/worktrees"

# Worktree paths (set during setup, used by cleanup trap)
CLAUDE_WT=""
CODEX_WT=""
REPO_DIR=""

###############################################################################
# Helpers
###############################################################################
red()    { printf '\033[31m%s\033[0m' "$*"; }
green()  { printf '\033[32m%s\033[0m' "$*"; }
yellow() { printf '\033[33m%s\033[0m' "$*"; }
cyan()   { printf '\033[36m%s\033[0m' "$*"; }
bold()   { printf '\033[1m%s\033[0m' "$*"; }

log() { echo "$(cyan "[ab-test]") $*"; }
err() { echo "$(red "[ab-test] ERROR:") $*" >&2; }

fmt_duration() {
  local secs=$1
  printf '%dm%02ds' $((secs / 60)) $((secs % 60))
}

cleanup() {
  log "Cleaning up worktrees..."
  if [[ -n "$CLAUDE_WT" && -d "$CLAUDE_WT" ]]; then
    git -C "$REPO_DIR" worktree remove --force "$CLAUDE_WT" 2>/dev/null || rm -rf "$CLAUDE_WT"
  fi
  if [[ -n "$CODEX_WT" && -d "$CODEX_WT" ]]; then
    git -C "$REPO_DIR" worktree remove --force "$CODEX_WT" 2>/dev/null || rm -rf "$CODEX_WT"
  fi
  if [[ -n "$REPO_DIR" ]]; then
    git -C "$REPO_DIR" worktree prune 2>/dev/null || true
  fi
}
trap cleanup EXIT

###############################################################################
# Step 1: Validate arguments and dependencies
###############################################################################
if [[ $# -lt 1 ]]; then
  echo "Usage: $0 <github-issue-url>"
  echo "Example: $0 https://github.com/owner/repo/issues/42"
  exit 1
fi

ISSUE_URL="$1"

# Parse GitHub issue URL
if [[ "$ISSUE_URL" =~ ^https://github\.com/([^/]+)/([^/]+)/issues/([0-9]+)$ ]]; then
  OWNER="${BASH_REMATCH[1]}"
  REPO="${BASH_REMATCH[2]}"
  ISSUE_NUM="${BASH_REMATCH[3]}"
else
  err "Invalid GitHub issue URL: $ISSUE_URL"
  echo "Expected format: https://github.com/owner/repo/issues/N"
  exit 1
fi

# Check dependencies
missing=()
for cmd in gh git claude codex jq; do
  if ! command -v "$cmd" &>/dev/null; then
    missing+=("$cmd")
  fi
done
if [[ ${#missing[@]} -gt 0 ]]; then
  err "Missing required commands: ${missing[*]}"
  exit 1
fi

# Create results directory
RESULTS_DIR="$RESULTS_BASE/$(date +%Y-%m-%d-%H%M%S)"
mkdir -p "$RESULTS_DIR"

log "A/B Agent Test: $(bold "$OWNER/$REPO#$ISSUE_NUM")"
log "Results: $RESULTS_DIR"
log "Timeout: ${TIMEOUT_SECONDS}s per agent"

###############################################################################
# Step 2: Fetch issue and build prompt
###############################################################################
log "Fetching issue..."
gh issue view "$ISSUE_NUM" --repo "$OWNER/$REPO" --json title,body,comments \
  > "$RESULTS_DIR/issue.json"

TITLE=$(jq -r '.title' "$RESULTS_DIR/issue.json")
BODY=$(jq -r '.body // "(No description provided)"' "$RESULTS_DIR/issue.json")
COMMENTS=$(jq -r '
  if (.comments | length) > 0 then
    "## Comments\n\n" + ([.comments[] | "\(.author.login): \(.body)"] | join("\n\n"))
  else
    ""
  end
' "$RESULTS_DIR/issue.json")

log "Issue: $(bold "$TITLE")"

cat > "$RESULTS_DIR/prompt.txt" <<PROMPT
You are analyzing a GitHub issue for the repository $OWNER/$REPO.

First, read the codebase to understand the project architecture. Look for
overview docs, README files, and key source files. Then create a detailed
implementation plan for the following issue.

## Issue: $TITLE

$BODY

$COMMENTS

## Instructions

Produce an implementation plan that:
- References specific files and functions in the repository
- Describes what changes to make and why
- Identifies edge cases and potential risks
- Suggests a testing approach
- Estimates scope (number of files, rough complexity)

Do NOT implement the changes. Only produce the plan.
PROMPT

###############################################################################
# Step 3: Clone repo and create worktrees
###############################################################################
REPO_DIR="$REPO_BASE/$OWNER/$REPO"

if [[ ! -d "$REPO_DIR/.git" ]]; then
  log "Cloning $OWNER/$REPO..."
  mkdir -p "$(dirname "$REPO_DIR")"
  gh repo clone "$OWNER/$REPO" "$REPO_DIR"
fi

log "Fetching latest..."
git -C "$REPO_DIR" fetch origin --quiet

DEFAULT_BRANCH=$(gh repo view "$OWNER/$REPO" --json defaultBranchRef --jq '.defaultBranchRef.name')

CLAUDE_WT="$WT_BASE/$OWNER/$REPO/claude-$$"
CODEX_WT="$WT_BASE/$OWNER/$REPO/codex-$$"

mkdir -p "$(dirname "$CLAUDE_WT")" "$(dirname "$CODEX_WT")"

log "Creating worktrees on $(bold "$DEFAULT_BRANCH")..."
git -C "$REPO_DIR" worktree add --detach "$CLAUDE_WT" "origin/$DEFAULT_BRANCH" --quiet
git -C "$REPO_DIR" worktree add --detach "$CODEX_WT" "origin/$DEFAULT_BRANCH" --quiet

###############################################################################
# Step 4: Run agents in parallel
###############################################################################
log "Running agents in parallel (timeout: ${TIMEOUT_SECONDS}s)..."

claude_start=$SECONDS
(
  cd "$CLAUDE_WT"
  timeout "$TIMEOUT_SECONDS" claude -p --dangerously-skip-permissions \
    < "$RESULTS_DIR/prompt.txt" \
    > "$RESULTS_DIR/claude-output.txt" 2>"$RESULTS_DIR/claude-stderr.txt"
) &
CLAUDE_PID=$!

codex_start=$SECONDS
(
  cd "$CODEX_WT"
  timeout "$TIMEOUT_SECONDS" codex exec --full-auto - \
    < "$RESULTS_DIR/prompt.txt" \
    > "$RESULTS_DIR/codex-output.txt" 2>"$RESULTS_DIR/codex-stderr.txt"
) &
CODEX_PID=$!

# Wait for both agents
claude_rc=0
wait "$CLAUDE_PID" || claude_rc=$?
claude_duration=$((SECONDS - claude_start))

codex_rc=0
wait "$CODEX_PID" || codex_rc=$?
codex_duration=$((SECONDS - codex_start))

if [[ $claude_rc -ne 0 ]]; then
  if [[ $claude_rc -eq 124 ]]; then
    log "$(yellow "Claude timed out after ${TIMEOUT_SECONDS}s")"
  else
    log "$(yellow "Claude exited with code $claude_rc")"
  fi
fi

if [[ $codex_rc -ne 0 ]]; then
  if [[ $codex_rc -eq 124 ]]; then
    log "$(yellow "Codex timed out after ${TIMEOUT_SECONDS}s")"
  else
    log "$(yellow "Codex exited with code $codex_rc")"
  fi
fi

claude_size=$(wc -c < "$RESULTS_DIR/claude-output.txt" 2>/dev/null || echo 0)
codex_size=$(wc -c < "$RESULTS_DIR/codex-output.txt" 2>/dev/null || echo 0)

log "Claude: $(fmt_duration "$claude_duration"), ${claude_size} bytes output"
log "Codex:  $(fmt_duration "$codex_duration"), ${codex_size} bytes output"

# Check if we have enough output to judge
if [[ "$claude_size" -lt 10 && "$codex_size" -lt 10 ]]; then
  err "Both agents produced no meaningful output. Cannot judge."
  exit 1
fi

###############################################################################
# Step 5: AI Judge
###############################################################################
log "Running AI judge..."

CLAUDE_OUTPUT=$(cat "$RESULTS_DIR/claude-output.txt")
CODEX_OUTPUT=$(cat "$RESULTS_DIR/codex-output.txt")

# Randomly assign to Plan A / Plan B to prevent positional bias
if (( RANDOM % 2 == 0 )); then
  PLAN_A_SOURCE="claude"
  PLAN_B_SOURCE="codex"
  PLAN_A_OUTPUT="$CLAUDE_OUTPUT"
  PLAN_B_OUTPUT="$CODEX_OUTPUT"
else
  PLAN_A_SOURCE="codex"
  PLAN_B_SOURCE="claude"
  PLAN_A_OUTPUT="$CODEX_OUTPUT"
  PLAN_B_OUTPUT="$CLAUDE_OUTPUT"
fi

JUDGE_PROMPT="You are evaluating two implementation plans for the same GitHub issue.
Both plans were generated by AI agents working in the same repository.

## Issue: $TITLE

$BODY

## Plan A

$PLAN_A_OUTPUT

## Plan B

$PLAN_B_OUTPUT

## Evaluation Criteria

Score each plan on a 1-5 scale for each criterion:

1. **specificity** — Does it reference actual files, functions, and patterns
   from the repository? (1 = vague hand-waving, 5 = precise file:function refs)
2. **actionability** — Could a developer implement directly from this plan
   without further research? (1 = needs much clarification, 5 = ready to code)
3. **scopeAwareness** — Is the scope appropriate for the issue? Not over-
   engineered or under-scoped? (1 = wildly off, 5 = perfectly scoped)
4. **codebaseUnderstanding** — Does the plan demonstrate actual knowledge of
   the repository's architecture, patterns, and conventions?
   (1 = generic advice, 5 = deep repo knowledge)

## Output Format

Return ONLY valid JSON with no code fences, no markdown, no explanation:
{
  \"scores\": {
    \"planA\": {\"specificity\": N, \"actionability\": N, \"scopeAwareness\": N, \"codebaseUnderstanding\": N},
    \"planB\": {\"specificity\": N, \"actionability\": N, \"scopeAwareness\": N, \"codebaseUnderstanding\": N}
  },
  \"winner\": \"planA or planB or tie\",
  \"reasoning\": \"Brief explanation of why the winner is better\"
}"

run_judge() {
  echo "$JUDGE_PROMPT" | claude -p --dangerously-skip-permissions 2>/dev/null
}

# Extract JSON from response (strip code fences if present)
extract_json() {
  local input="$1"
  # Try direct parse first
  if echo "$input" | jq . 2>/dev/null; then
    return 0
  fi
  # Strip code fences and try again
  # shellcheck disable=SC2016
  echo "$input" | sed -n '/^```/,/^```/{ /^```/d; p; }' | jq .
}

JUDGE_RAW=$(run_judge)
JUDGE_JSON=$(extract_json "$JUDGE_RAW" 2>/dev/null) || true

# Retry once if parse failed
if [[ -z "$JUDGE_JSON" ]]; then
  log "$(yellow "Judge JSON parse failed, retrying...")"
  JUDGE_RAW=$(run_judge)
  JUDGE_JSON=$(extract_json "$JUDGE_RAW" 2>/dev/null) || true
fi

if [[ -z "$JUDGE_JSON" ]]; then
  err "Could not parse judge output as JSON after 2 attempts."
  echo "$JUDGE_RAW" > "$RESULTS_DIR/judge-raw-output.txt"
  log "Raw judge output saved to $RESULTS_DIR/judge-raw-output.txt"

  # Still print what we can
  echo ""
  echo "=== Raw Judge Output ==="
  echo "$JUDGE_RAW"
  echo ""
  log "Plan A was: $PLAN_A_SOURCE"
  log "Plan B was: $PLAN_B_SOURCE"
  exit 0
fi

# Map Plan A/B scores back to claude/codex
if [[ "$PLAN_A_SOURCE" == "claude" ]]; then
  CLAUDE_SCORES=$(echo "$JUDGE_JSON" | jq '.scores.planA')
  CODEX_SCORES=$(echo "$JUDGE_JSON" | jq '.scores.planB')
else
  CLAUDE_SCORES=$(echo "$JUDGE_JSON" | jq '.scores.planB')
  CODEX_SCORES=$(echo "$JUDGE_JSON" | jq '.scores.planA')
fi

WINNER_AB=$(echo "$JUDGE_JSON" | jq -r '.winner')
REASONING=$(echo "$JUDGE_JSON" | jq -r '.reasoning')

# Map winner from planA/planB to agent name
if [[ "$WINNER_AB" == "planA" ]]; then
  WINNER="$PLAN_A_SOURCE"
elif [[ "$WINNER_AB" == "planB" ]]; then
  WINNER="$PLAN_B_SOURCE"
else
  WINNER="tie"
fi

# Build final judge output with agent names
jq -n \
  --argjson claude "$CLAUDE_SCORES" \
  --argjson codex "$CODEX_SCORES" \
  --arg winner "$WINNER" \
  --arg reasoning "$REASONING" \
  --arg planA_source "$PLAN_A_SOURCE" \
  --arg planB_source "$PLAN_B_SOURCE" \
  '{
    scores: { claude: $claude, codex: $codex },
    winner: $winner,
    reasoning: $reasoning,
    randomization: { planA: $planA_source, planB: $planB_source }
  }' > "$RESULTS_DIR/judge-output.json"

###############################################################################
# Step 6: Print summary
###############################################################################
cs() { echo "$CLAUDE_SCORES" | jq -r ".$1"; }
xs() { echo "$CODEX_SCORES" | jq -r ".$1"; }

claude_total=$(( $(cs specificity) + $(cs actionability) + $(cs scopeAwareness) + $(cs codebaseUnderstanding) ))
codex_total=$(( $(xs specificity) + $(xs actionability) + $(xs scopeAwareness) + $(xs codebaseUnderstanding) ))

print_summary() {
  local color=$1  # 1 = colorized, 0 = plain

  line() {
    printf '  %-22s %6s %8s\n' "$1" "$2" "$3"
  }

  echo "==========================================="
  echo "  A/B Agent Test: $OWNER/$REPO#$ISSUE_NUM"
  echo "  \"$TITLE\""
  echo "==========================================="
  echo ""
  echo "  Scores (1-5):"
  printf '  %-22s %6s %8s\n' "" "Claude" "Codex"
  line "Specificity" "$(cs specificity)" "$(xs specificity)"
  line "Actionability" "$(cs actionability)" "$(xs actionability)"
  line "Scope Awareness" "$(cs scopeAwareness)" "$(xs scopeAwareness)"
  line "Codebase Knowledge" "$(cs codebaseUnderstanding)" "$(xs codebaseUnderstanding)"
  echo "  ─────────────────────────────────────────"
  printf '  %-22s %6s %8s\n' "Total" "$claude_total" "$codex_total"
  echo ""
  printf '  %-22s %6s %8s\n' "Time" "$(fmt_duration "$claude_duration")" "$(fmt_duration "$codex_duration")"
  echo ""

  local winner_cap="${WINNER^}"
  if [[ "$WINNER" == "tie" ]]; then
    echo "  Winner: TIE"
  elif [[ $color -eq 1 ]]; then
    echo "  Winner: $(green "$winner_cap")"
  else
    echo "  Winner: $winner_cap"
  fi
  echo ""
  echo "  Reasoning: $REASONING"
  echo ""
  echo "  Full outputs:"
  echo "    Claude: $RESULTS_DIR/claude-output.txt"
  echo "    Codex:  $RESULTS_DIR/codex-output.txt"
  echo "    Judge:  $RESULTS_DIR/judge-output.json"
  echo "==========================================="
}

echo ""
print_summary 1

# Save plain-text summary
print_summary 0 > "$RESULTS_DIR/summary.txt"

log "Done. Results saved to $RESULTS_DIR"
